SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `localtest7` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `localtest7` ;

CREATE TABLE IF NOT EXISTS colaborator_address (
  id_colaborator_address INT NOT NULL AUTO_INCREMENT,
  cep INT NULL DEFAULT NULL,
  street VARCHAR(100) NULL DEFAULT NULL,
  number INT NULL DEFAULT NULL,
  district VARCHAR(100) NULL DEFAULT NULL,
  city VARCHAR(45) NULL DEFAULT NULL,
  state VARCHAR(45) NULL DEFAULT NULL,
  country VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (id_colaborator_address))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS colaborator_type (
  id_colaborator_type INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (id_colaborator_type))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS colaborator (
  id_colaborator INT NOT NULL AUTO_INCREMENT,
  id_colaborator_type INT NOT NULL,
  id_colaborator_address INT NOT NULL,
  cnpj INT NULL DEFAULT NULL,
  name VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (id_colaborator),
  INDEX fk_colaborator_colaborator_type_idx (id_colaborator_type ASC) VISIBLE,
  INDEX fk_colaborator_colaborator_address1_idx (id_colaborator_address ASC) VISIBLE,
  CONSTRAINT fk_colaborator_colaborator_address
    FOREIGN KEY (id_colaborator_address)
    REFERENCES colaborator_address (id_colaborator_address)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_colaborator_colaborator_type
    FOREIGN KEY (id_colaborator_type)
    REFERENCES colaborator_type (id_colaborator_type)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS flsolutions_adminlog (
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  module VARCHAR(50) NOT NULL DEFAULT '',
  action VARCHAR(50) NOT NULL DEFAULT '',
  data TEXT NOT NULL,
  INDEX module (module ASC, action ASC) VISIBLE,
  INDEX uid (uid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_adminoptions (
  uid INT NOT NULL DEFAULT '0',
  cpstyle VARCHAR(50) NOT NULL DEFAULT '',
  cplanguage VARCHAR(50) NOT NULL DEFAULT '',
  codepress TINYINT(1) NOT NULL DEFAULT '1',
  notes TEXT NOT NULL,
  permissions TEXT NOT NULL,
  defaultviews TEXT NOT NULL,
  loginattempts SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  loginlockoutexpiry INT UNSIGNED NOT NULL DEFAULT '0',
  authsecret VARCHAR(16) NOT NULL DEFAULT '',
  recovery_codes VARCHAR(177) NOT NULL DEFAULT '',
  PRIMARY KEY (uid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_adminsessions (
  sid VARCHAR(32) NOT NULL DEFAULT '',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  loginkey VARCHAR(50) NOT NULL DEFAULT '',
  ip VARBINARY(16) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  lastactive INT UNSIGNED NOT NULL DEFAULT '0',
  data TEXT NOT NULL,
  useragent VARCHAR(200) NOT NULL DEFAULT '',
  authenticated TINYINT(1) NOT NULL DEFAULT '0')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_adminviews (
  vid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  title VARCHAR(100) NOT NULL DEFAULT '',
  type VARCHAR(6) NOT NULL DEFAULT '',
  visibility TINYINT(1) NOT NULL DEFAULT '0',
  fields TEXT NOT NULL,
  conditions TEXT NOT NULL,
  custom_profile_fields TEXT NOT NULL,
  sortby VARCHAR(20) NOT NULL DEFAULT '',
  sortorder VARCHAR(4) NOT NULL DEFAULT '',
  perpage SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  view_type VARCHAR(6) NOT NULL DEFAULT '',
  PRIMARY KEY (vid))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_announcements (
  aid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  fid INT NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  subject VARCHAR(120) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  startdate INT UNSIGNED NOT NULL DEFAULT '0',
  enddate INT UNSIGNED NOT NULL DEFAULT '0',
  allowhtml TINYINT(1) NOT NULL DEFAULT '0',
  allowmycode TINYINT(1) NOT NULL DEFAULT '0',
  allowsmilies TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (aid),
  INDEX fid (fid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_attachments (
  aid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pid INT UNSIGNED NOT NULL DEFAULT '0',
  posthash VARCHAR(50) NOT NULL DEFAULT '',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  filename VARCHAR(255) NOT NULL DEFAULT '',
  filetype VARCHAR(120) NOT NULL DEFAULT '',
  filesize INT UNSIGNED NOT NULL DEFAULT '0',
  attachname VARCHAR(255) NOT NULL DEFAULT '',
  downloads INT UNSIGNED NOT NULL DEFAULT '0',
  dateuploaded INT UNSIGNED NOT NULL DEFAULT '0',
  visible TINYINT(1) NOT NULL DEFAULT '0',
  thumbnail VARCHAR(120) NOT NULL DEFAULT '',
  PRIMARY KEY (aid),
  INDEX pid (pid ASC, visible ASC) VISIBLE,
  INDEX uid (uid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_attachtypes (
  atid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL DEFAULT '',
  mimetype VARCHAR(120) NOT NULL DEFAULT '',
  extension VARCHAR(10) NOT NULL DEFAULT '',
  maxsize INT UNSIGNED NOT NULL DEFAULT '0',
  icon VARCHAR(100) NOT NULL DEFAULT '',
  enabled TINYINT(1) NOT NULL DEFAULT '1',
  groups TEXT NOT NULL,
  forums TEXT NOT NULL,
  avatarfile TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (atid))
ENGINE = MyISAM
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_awaitingactivation (
  aid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  code VARCHAR(100) NOT NULL DEFAULT '',
  type CHAR(1) NOT NULL DEFAULT '',
  validated TINYINT(1) NOT NULL DEFAULT '0',
  misc VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (aid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_badwords (
  bid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  badword VARCHAR(100) NOT NULL DEFAULT '',
  regex TINYINT(1) NOT NULL DEFAULT '0',
  replacement VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (bid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_banfilters (
  fid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  filter VARCHAR(200) NOT NULL DEFAULT '',
  type TINYINT(1) NOT NULL DEFAULT '0',
  lastuse INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (fid),
  INDEX type (type ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_banned (
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  gid INT UNSIGNED NOT NULL DEFAULT '0',
  oldgroup INT UNSIGNED NOT NULL DEFAULT '0',
  oldadditionalgroups TEXT NOT NULL,
  olddisplaygroup INT UNSIGNED NOT NULL DEFAULT '0',
  admin INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  bantime VARCHAR(50) NOT NULL DEFAULT '',
  lifted INT UNSIGNED NOT NULL DEFAULT '0',
  reason VARCHAR(255) NOT NULL DEFAULT '',
  INDEX uid (uid ASC) VISIBLE,
  INDEX dateline (dateline ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_buddyrequests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  touid INT UNSIGNED NOT NULL DEFAULT '0',
  date INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  INDEX uid (uid ASC) VISIBLE,
  INDEX touid (touid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_calendarpermissions (
  cid INT UNSIGNED NOT NULL DEFAULT '0',
  gid INT UNSIGNED NOT NULL DEFAULT '0',
  canviewcalendar TINYINT(1) NOT NULL DEFAULT '0',
  canaddevents TINYINT(1) NOT NULL DEFAULT '0',
  canbypasseventmod TINYINT(1) NOT NULL DEFAULT '0',
  canmoderateevents TINYINT(1) NOT NULL DEFAULT '0')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_calendars (
  cid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL DEFAULT '',
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  startofweek TINYINT(1) NOT NULL DEFAULT '0',
  showbirthdays TINYINT(1) NOT NULL DEFAULT '0',
  eventlimit SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  moderation TINYINT(1) NOT NULL DEFAULT '0',
  allowhtml TINYINT(1) NOT NULL DEFAULT '0',
  allowmycode TINYINT(1) NOT NULL DEFAULT '0',
  allowimgcode TINYINT(1) NOT NULL DEFAULT '0',
  allowvideocode TINYINT(1) NOT NULL DEFAULT '0',
  allowsmilies TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (cid))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_captcha (
  imagehash VARCHAR(32) NOT NULL DEFAULT '',
  imagestring VARCHAR(8) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  used TINYINT(1) NOT NULL DEFAULT '0',
  INDEX imagehash (imagehash ASC) VISIBLE,
  INDEX dateline (dateline ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_datacache (
  title VARCHAR(50) NOT NULL DEFAULT '',
  cache MEDIUMTEXT NOT NULL,
  PRIMARY KEY (title))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_delayedmoderation (
  did INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type VARCHAR(30) NOT NULL DEFAULT '',
  delaydateline INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  fid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  tids TEXT NOT NULL,
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  inputs TEXT NOT NULL,
  PRIMARY KEY (did))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_events (
  eid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  cid INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  name VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  visible TINYINT(1) NOT NULL DEFAULT '0',
  private TINYINT(1) NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  starttime INT UNSIGNED NOT NULL DEFAULT '0',
  endtime INT UNSIGNED NOT NULL DEFAULT '0',
  timezone VARCHAR(5) NOT NULL DEFAULT '',
  ignoretimezone TINYINT(1) NOT NULL DEFAULT '0',
  usingtime TINYINT(1) NOT NULL DEFAULT '0',
  repeats TEXT NOT NULL,
  PRIMARY KEY (eid),
  INDEX cid (cid ASC) VISIBLE,
  INDEX daterange (starttime ASC, endtime ASC) VISIBLE,
  INDEX private (private ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_forumpermissions (
  pid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  fid INT UNSIGNED NOT NULL DEFAULT '0',
  gid INT UNSIGNED NOT NULL DEFAULT '0',
  canview TINYINT(1) NOT NULL DEFAULT '0',
  canviewthreads TINYINT(1) NOT NULL DEFAULT '0',
  canonlyviewownthreads TINYINT(1) NOT NULL DEFAULT '0',
  candlattachments TINYINT(1) NOT NULL DEFAULT '0',
  canpostthreads TINYINT(1) NOT NULL DEFAULT '0',
  canpostreplys TINYINT(1) NOT NULL DEFAULT '0',
  canonlyreplyownthreads TINYINT(1) NOT NULL DEFAULT '0',
  canpostattachments TINYINT(1) NOT NULL DEFAULT '0',
  canratethreads TINYINT(1) NOT NULL DEFAULT '0',
  caneditposts TINYINT(1) NOT NULL DEFAULT '0',
  candeleteposts TINYINT(1) NOT NULL DEFAULT '0',
  candeletethreads TINYINT(1) NOT NULL DEFAULT '0',
  caneditattachments TINYINT(1) NOT NULL DEFAULT '0',
  canviewdeletionnotice TINYINT(1) NOT NULL DEFAULT '0',
  modposts TINYINT(1) NOT NULL DEFAULT '0',
  modthreads TINYINT(1) NOT NULL DEFAULT '0',
  mod_edit_posts TINYINT(1) NOT NULL DEFAULT '0',
  modattachments TINYINT(1) NOT NULL DEFAULT '0',
  canpostpolls TINYINT(1) NOT NULL DEFAULT '0',
  canvotepolls TINYINT(1) NOT NULL DEFAULT '0',
  cansearch TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (pid),
  INDEX fid (fid ASC, gid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_forums (
  fid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  linkto VARCHAR(180) NOT NULL DEFAULT '',
  type CHAR(1) NOT NULL DEFAULT '',
  pid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  parentlist TEXT NOT NULL,
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  active TINYINT(1) NOT NULL DEFAULT '0',
  open TINYINT(1) NOT NULL DEFAULT '0',
  threads INT UNSIGNED NOT NULL DEFAULT '0',
  posts INT UNSIGNED NOT NULL DEFAULT '0',
  lastpost INT UNSIGNED NOT NULL DEFAULT '0',
  lastposter VARCHAR(120) NOT NULL DEFAULT '',
  lastposteruid INT UNSIGNED NOT NULL DEFAULT '0',
  lastposttid INT UNSIGNED NOT NULL DEFAULT '0',
  lastpostsubject VARCHAR(120) NOT NULL DEFAULT '',
  allowhtml TINYINT(1) NOT NULL DEFAULT '0',
  allowmycode TINYINT(1) NOT NULL DEFAULT '0',
  allowsmilies TINYINT(1) NOT NULL DEFAULT '0',
  allowimgcode TINYINT(1) NOT NULL DEFAULT '0',
  allowvideocode TINYINT(1) NOT NULL DEFAULT '0',
  allowpicons TINYINT(1) NOT NULL DEFAULT '0',
  allowtratings TINYINT(1) NOT NULL DEFAULT '0',
  usepostcounts TINYINT(1) NOT NULL DEFAULT '0',
  usethreadcounts TINYINT(1) NOT NULL DEFAULT '0',
  requireprefix TINYINT(1) NOT NULL DEFAULT '0',
  password VARCHAR(50) NOT NULL DEFAULT '',
  showinjump TINYINT(1) NOT NULL DEFAULT '0',
  style SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  overridestyle TINYINT(1) NOT NULL DEFAULT '0',
  rulestype TINYINT(1) NOT NULL DEFAULT '0',
  rulestitle VARCHAR(200) NOT NULL DEFAULT '',
  rules TEXT NOT NULL,
  unapprovedthreads INT UNSIGNED NOT NULL DEFAULT '0',
  unapprovedposts INT UNSIGNED NOT NULL DEFAULT '0',
  deletedthreads INT UNSIGNED NOT NULL DEFAULT '0',
  deletedposts INT UNSIGNED NOT NULL DEFAULT '0',
  defaultdatecut SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  defaultsortby VARCHAR(10) NOT NULL DEFAULT '',
  defaultsortorder VARCHAR(4) NOT NULL DEFAULT '',
  PRIMARY KEY (fid))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_forumsread (
  fid INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  UNIQUE INDEX fid (fid ASC, uid ASC) VISIBLE,
  INDEX dateline (dateline ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_forumsubscriptions (
  fsid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  fid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (fsid),
  INDEX uid (uid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_groupleaders (
  lid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  gid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  canmanagemembers TINYINT(1) NOT NULL DEFAULT '0',
  canmanagerequests TINYINT(1) NOT NULL DEFAULT '0',
  caninvitemembers TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (lid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_helpdocs (
  hid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  name VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  document TEXT NOT NULL,
  usetranslation TINYINT(1) NOT NULL DEFAULT '0',
  enabled TINYINT(1) NOT NULL DEFAULT '0',
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (hid))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_helpsections (
  sid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  usetranslation TINYINT(1) NOT NULL DEFAULT '0',
  enabled TINYINT(1) NOT NULL DEFAULT '0',
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (sid))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_icons (
  iid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL DEFAULT '',
  path VARCHAR(220) NOT NULL DEFAULT '',
  PRIMARY KEY (iid))
ENGINE = MyISAM
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_joinrequests (
  rid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  gid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  reason VARCHAR(250) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  invite TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (rid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_mailerrors (
  eid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  subject VARCHAR(200) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  toaddress VARCHAR(150) NOT NULL DEFAULT '',
  fromaddress VARCHAR(150) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  error TEXT NOT NULL,
  smtperror VARCHAR(200) NOT NULL DEFAULT '',
  smtpcode SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (eid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_maillogs (
  mid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  subject VARCHAR(200) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  fromuid INT UNSIGNED NOT NULL DEFAULT '0',
  fromemail VARCHAR(200) NOT NULL DEFAULT '',
  touid INT UNSIGNED NOT NULL DEFAULT '0',
  toemail VARCHAR(200) NOT NULL DEFAULT '',
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  type TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (mid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_mailqueue (
  mid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mailto VARCHAR(200) NOT NULL,
  mailfrom VARCHAR(200) NOT NULL,
  subject VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  headers TEXT NOT NULL,
  PRIMARY KEY (mid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_massemails (
  mid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  subject VARCHAR(200) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  htmlmessage TEXT NOT NULL,
  type TINYINT(1) NOT NULL DEFAULT '0',
  format TINYINT(1) NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  senddate INT UNSIGNED NOT NULL DEFAULT '0',
  status TINYINT(1) NOT NULL DEFAULT '0',
  sentcount INT UNSIGNED NOT NULL DEFAULT '0',
  totalcount INT UNSIGNED NOT NULL DEFAULT '0',
  conditions TEXT NOT NULL,
  perpage SMALLINT UNSIGNED NOT NULL DEFAULT '50',
  PRIMARY KEY (mid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_moderatorlog (
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  fid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  pid INT UNSIGNED NOT NULL DEFAULT '0',
  action TEXT NOT NULL,
  data TEXT NOT NULL,
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  INDEX uid (uid ASC) VISIBLE,
  INDEX fid (fid ASC) VISIBLE,
  INDEX tid (tid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_moderators (
  mid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  fid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  id INT UNSIGNED NOT NULL DEFAULT '0',
  isgroup TINYINT UNSIGNED NOT NULL DEFAULT '0',
  caneditposts TINYINT(1) NOT NULL DEFAULT '0',
  cansoftdeleteposts TINYINT(1) NOT NULL DEFAULT '0',
  canrestoreposts TINYINT(1) NOT NULL DEFAULT '0',
  candeleteposts TINYINT(1) NOT NULL DEFAULT '0',
  cansoftdeletethreads TINYINT(1) NOT NULL DEFAULT '0',
  canrestorethreads TINYINT(1) NOT NULL DEFAULT '0',
  candeletethreads TINYINT(1) NOT NULL DEFAULT '0',
  canviewips TINYINT(1) NOT NULL DEFAULT '0',
  canviewunapprove TINYINT(1) NOT NULL DEFAULT '0',
  canviewdeleted TINYINT(1) NOT NULL DEFAULT '0',
  canopenclosethreads TINYINT(1) NOT NULL DEFAULT '0',
  canstickunstickthreads TINYINT(1) NOT NULL DEFAULT '0',
  canapproveunapprovethreads TINYINT(1) NOT NULL DEFAULT '0',
  canapproveunapproveposts TINYINT(1) NOT NULL DEFAULT '0',
  canapproveunapproveattachs TINYINT(1) NOT NULL DEFAULT '0',
  canmanagethreads TINYINT(1) NOT NULL DEFAULT '0',
  canmanagepolls TINYINT(1) NOT NULL DEFAULT '0',
  canpostclosedthreads TINYINT(1) NOT NULL DEFAULT '0',
  canmovetononmodforum TINYINT(1) NOT NULL DEFAULT '0',
  canusecustomtools TINYINT(1) NOT NULL DEFAULT '0',
  canmanageannouncements TINYINT(1) NOT NULL DEFAULT '0',
  canmanagereportedposts TINYINT(1) NOT NULL DEFAULT '0',
  canviewmodlog TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (mid),
  INDEX uid (id ASC, fid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_modtools (
  tid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  forums TEXT NOT NULL,
  groups TEXT NOT NULL,
  type CHAR(1) NOT NULL DEFAULT '',
  postoptions TEXT NOT NULL,
  threadoptions TEXT NOT NULL,
  PRIMARY KEY (tid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_mycode (
  cid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  regex TEXT NOT NULL,
  replacement TEXT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT '0',
  parseorder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (cid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_polls (
  pid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  question VARCHAR(200) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  options TEXT NOT NULL,
  votes TEXT NOT NULL,
  numoptions SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  numvotes INT UNSIGNED NOT NULL DEFAULT '0',
  timeout INT UNSIGNED NOT NULL DEFAULT '0',
  closed TINYINT(1) NOT NULL DEFAULT '0',
  multiple TINYINT(1) NOT NULL DEFAULT '0',
  public TINYINT(1) NOT NULL DEFAULT '0',
  maxoptions SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (pid),
  INDEX tid (tid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_pollvotes (
  vid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pid INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  voteoption SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  PRIMARY KEY (vid),
  INDEX pid (pid ASC, uid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_posts (
  pid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  replyto INT UNSIGNED NOT NULL DEFAULT '0',
  fid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  subject VARCHAR(120) NOT NULL DEFAULT '',
  icon SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  username VARCHAR(80) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  message TEXT NOT NULL,
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  includesig TINYINT(1) NOT NULL DEFAULT '0',
  smilieoff TINYINT(1) NOT NULL DEFAULT '0',
  edituid INT UNSIGNED NOT NULL DEFAULT '0',
  edittime INT UNSIGNED NOT NULL DEFAULT '0',
  editreason VARCHAR(150) NOT NULL DEFAULT '',
  visible TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (pid),
  INDEX tid (tid ASC, uid ASC) VISIBLE,
  INDEX uid (uid ASC) VISIBLE,
  INDEX visible (visible ASC) VISIBLE,
  INDEX dateline (dateline ASC) VISIBLE,
  INDEX ipaddress (ipaddress ASC) VISIBLE,
  INDEX tiddate (tid ASC, dateline ASC) VISIBLE,
  FULLTEXT INDEX message (message) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_privatemessages (
  pmid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  toid INT UNSIGNED NOT NULL DEFAULT '0',
  fromid INT UNSIGNED NOT NULL DEFAULT '0',
  recipients TEXT NOT NULL,
  folder SMALLINT UNSIGNED NOT NULL DEFAULT '1',
  subject VARCHAR(120) NOT NULL DEFAULT '',
  icon SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  message TEXT NOT NULL,
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  deletetime INT UNSIGNED NOT NULL DEFAULT '0',
  status TINYINT(1) NOT NULL DEFAULT '0',
  statustime INT UNSIGNED NOT NULL DEFAULT '0',
  includesig TINYINT(1) NOT NULL DEFAULT '0',
  smilieoff TINYINT(1) NOT NULL DEFAULT '0',
  receipt TINYINT(1) NOT NULL DEFAULT '0',
  readtime INT UNSIGNED NOT NULL DEFAULT '0',
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  PRIMARY KEY (pmid),
  INDEX uid (uid ASC, folder ASC) VISIBLE,
  INDEX toid (toid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_profilefields (
  fid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  type TEXT NOT NULL,
  regex TEXT NOT NULL,
  length SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  maxlength SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  required TINYINT(1) NOT NULL DEFAULT '0',
  registration TINYINT(1) NOT NULL DEFAULT '0',
  profile TINYINT(1) NOT NULL DEFAULT '0',
  postbit TINYINT(1) NOT NULL DEFAULT '0',
  viewableby TEXT NOT NULL,
  editableby TEXT NOT NULL,
  postnum SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  allowhtml TINYINT(1) NOT NULL DEFAULT '0',
  allowmycode TINYINT(1) NOT NULL DEFAULT '0',
  allowsmilies TINYINT(1) NOT NULL DEFAULT '0',
  allowimgcode TINYINT(1) NOT NULL DEFAULT '0',
  allowvideocode TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (fid))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_promotionlogs (
  plid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pid INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  oldusergroup VARCHAR(200) NOT NULL DEFAULT '0',
  newusergroup SMALLINT NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  type VARCHAR(9) NOT NULL DEFAULT 'primary',
  PRIMARY KEY (plid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_promotions (
  pid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT '1',
  logging TINYINT(1) NOT NULL DEFAULT '0',
  posts INT UNSIGNED NOT NULL DEFAULT '0',
  posttype CHAR(2) NOT NULL DEFAULT '',
  threads INT UNSIGNED NOT NULL DEFAULT '0',
  threadtype CHAR(2) NOT NULL DEFAULT '',
  registered INT UNSIGNED NOT NULL DEFAULT '0',
  registeredtype VARCHAR(20) NOT NULL DEFAULT '',
  online INT UNSIGNED NOT NULL DEFAULT '0',
  onlinetype VARCHAR(20) NOT NULL DEFAULT '',
  reputations INT NOT NULL DEFAULT '0',
  reputationtype CHAR(2) NOT NULL DEFAULT '',
  referrals INT UNSIGNED NOT NULL DEFAULT '0',
  referralstype CHAR(2) NOT NULL DEFAULT '',
  warnings INT UNSIGNED NOT NULL DEFAULT '0',
  warningstype CHAR(2) NOT NULL DEFAULT '',
  requirements VARCHAR(200) NOT NULL DEFAULT '',
  originalusergroup VARCHAR(120) NOT NULL DEFAULT '0',
  newusergroup SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  usergrouptype VARCHAR(120) NOT NULL DEFAULT '0',
  PRIMARY KEY (pid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_questions (
  qid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  question VARCHAR(200) NOT NULL DEFAULT '',
  answer VARCHAR(150) NOT NULL DEFAULT '',
  shown INT UNSIGNED NOT NULL DEFAULT '0',
  correct INT UNSIGNED NOT NULL DEFAULT '0',
  incorrect INT UNSIGNED NOT NULL DEFAULT '0',
  active TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (qid))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_questionsessions (
  sid VARCHAR(32) NOT NULL DEFAULT '',
  qid INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (sid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_reportedcontent (
  rid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  id INT UNSIGNED NOT NULL DEFAULT '0',
  id2 INT UNSIGNED NOT NULL DEFAULT '0',
  id3 INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  reportstatus TINYINT(1) NOT NULL DEFAULT '0',
  reasonid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  reason VARCHAR(250) NOT NULL DEFAULT '',
  type VARCHAR(50) NOT NULL DEFAULT '',
  reports INT UNSIGNED NOT NULL DEFAULT '0',
  reporters TEXT NOT NULL,
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  lastreport INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (rid),
  INDEX reportstatus (reportstatus ASC) VISIBLE,
  INDEX lastreport (lastreport ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_reportreasons (
  rid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(250) NOT NULL DEFAULT '',
  appliesto VARCHAR(250) NOT NULL DEFAULT '',
  extra TINYINT(1) NOT NULL DEFAULT '0',
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (rid))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_reputation (
  rid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  adduid INT UNSIGNED NOT NULL DEFAULT '0',
  pid INT UNSIGNED NOT NULL DEFAULT '0',
  reputation SMALLINT NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  comments TEXT NOT NULL,
  PRIMARY KEY (rid),
  INDEX uid (uid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_searchlog (
  sid VARCHAR(32) NOT NULL DEFAULT '',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  threads LONGTEXT NOT NULL,
  posts LONGTEXT NOT NULL,
  resulttype VARCHAR(10) NOT NULL DEFAULT '',
  querycache TEXT NOT NULL,
  keywords TEXT NOT NULL,
  PRIMARY KEY (sid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_sessions (
  sid VARCHAR(32) NOT NULL DEFAULT '',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  ip VARBINARY(16) NOT NULL DEFAULT '',
  time INT UNSIGNED NOT NULL DEFAULT '0',
  location VARCHAR(150) NOT NULL DEFAULT '',
  useragent VARCHAR(200) NOT NULL DEFAULT '',
  anonymous TINYINT(1) NOT NULL DEFAULT '0',
  nopermission TINYINT(1) NOT NULL DEFAULT '0',
  location1 INT UNSIGNED NOT NULL DEFAULT '0',
  location2 INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (sid),
  INDEX location (location1 ASC, location2 ASC) VISIBLE,
  INDEX time (time ASC) VISIBLE,
  INDEX uid (uid ASC) VISIBLE,
  INDEX ip (ip ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_settinggroups (
  gid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL DEFAULT '',
  title VARCHAR(220) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  isdefault TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (gid))
ENGINE = MyISAM
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_settings (
  sid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL DEFAULT '',
  title VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  optionscode TEXT NOT NULL,
  value TEXT NOT NULL,
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  gid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  isdefault TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (sid),
  INDEX gid (gid ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 291
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_smilies (
  sid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL DEFAULT '',
  find TEXT NOT NULL,
  image VARCHAR(220) NOT NULL DEFAULT '',
  disporder SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  showclickable TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (sid))
ENGINE = MyISAM
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_spamlog (
  sid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(120) NOT NULL DEFAULT '',
  email VARCHAR(220) NOT NULL DEFAULT '',
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  data TEXT NOT NULL,
  PRIMARY KEY (sid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_spiders (
  sid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL DEFAULT '',
  theme SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  language VARCHAR(20) NOT NULL DEFAULT '',
  usergroup SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  useragent VARCHAR(200) NOT NULL DEFAULT '',
  lastvisit INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (sid))
ENGINE = MyISAM
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_stats (
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  numusers INT UNSIGNED NOT NULL DEFAULT '0',
  numthreads INT UNSIGNED NOT NULL DEFAULT '0',
  numposts INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (dateline))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_tasklog (
  lid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  data TEXT NOT NULL,
  PRIMARY KEY (lid))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_tasks (
  tid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  file VARCHAR(30) NOT NULL DEFAULT '',
  minute VARCHAR(200) NOT NULL DEFAULT '',
  hour VARCHAR(200) NOT NULL DEFAULT '',
  day VARCHAR(100) NOT NULL DEFAULT '',
  month VARCHAR(30) NOT NULL DEFAULT '',
  weekday VARCHAR(15) NOT NULL DEFAULT '',
  nextrun INT UNSIGNED NOT NULL DEFAULT '0',
  lastrun INT UNSIGNED NOT NULL DEFAULT '0',
  enabled TINYINT(1) NOT NULL DEFAULT '1',
  logging TINYINT(1) NOT NULL DEFAULT '0',
  locked INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (tid))
ENGINE = MyISAM
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_templategroups (
  gid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  prefix VARCHAR(50) NOT NULL DEFAULT '',
  title VARCHAR(100) NOT NULL DEFAULT '',
  isdefault TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (gid))
ENGINE = MyISAM
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_templates (
  tid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(120) NOT NULL DEFAULT '',
  template TEXT NOT NULL,
  sid SMALLINT NOT NULL DEFAULT '0',
  version VARCHAR(20) NOT NULL DEFAULT '0',
  status VARCHAR(10) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (tid),
  INDEX sid (sid ASC, title ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 971
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_templatesets (
  sid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(120) NOT NULL DEFAULT '',
  PRIMARY KEY (sid))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_themes (
  tid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL DEFAULT '',
  pid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  def TINYINT(1) NOT NULL DEFAULT '0',
  properties TEXT NOT NULL,
  stylesheets TEXT NOT NULL,
  allowedgroups TEXT NOT NULL,
  PRIMARY KEY (tid))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_themestylesheets (
  sid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL DEFAULT '',
  tid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  attachedto TEXT NOT NULL,
  stylesheet LONGTEXT NOT NULL,
  cachefile VARCHAR(100) NOT NULL DEFAULT '',
  lastmodified INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (sid),
  INDEX tid (tid ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_threadprefixes (
  pid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  prefix VARCHAR(120) NOT NULL DEFAULT '',
  displaystyle VARCHAR(200) NOT NULL DEFAULT '',
  forums TEXT NOT NULL,
  groups TEXT NOT NULL,
  PRIMARY KEY (pid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_threadratings (
  rid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  rating TINYINT UNSIGNED NOT NULL DEFAULT '0',
  ipaddress VARBINARY(16) NOT NULL DEFAULT '',
  PRIMARY KEY (rid),
  INDEX tid (tid ASC, uid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_threads (
  tid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  fid SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  subject VARCHAR(120) NOT NULL DEFAULT '',
  prefix SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  icon SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  poll INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  username VARCHAR(80) NOT NULL DEFAULT '',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  firstpost INT UNSIGNED NOT NULL DEFAULT '0',
  lastpost INT UNSIGNED NOT NULL DEFAULT '0',
  lastposter VARCHAR(120) NOT NULL DEFAULT '',
  lastposteruid INT UNSIGNED NOT NULL DEFAULT '0',
  views INT UNSIGNED NOT NULL DEFAULT '0',
  replies INT UNSIGNED NOT NULL DEFAULT '0',
  closed VARCHAR(30) NOT NULL DEFAULT '',
  sticky TINYINT(1) NOT NULL DEFAULT '0',
  numratings SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  totalratings SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  notes TEXT NOT NULL,
  visible TINYINT(1) NOT NULL DEFAULT '0',
  unapprovedposts INT UNSIGNED NOT NULL DEFAULT '0',
  deletedposts INT UNSIGNED NOT NULL DEFAULT '0',
  attachmentcount INT UNSIGNED NOT NULL DEFAULT '0',
  deletetime INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (tid),
  INDEX fid (fid ASC, visible ASC, sticky ASC) VISIBLE,
  INDEX dateline (dateline ASC) VISIBLE,
  INDEX lastpost (lastpost ASC, fid ASC) VISIBLE,
  INDEX firstpost (firstpost ASC) VISIBLE,
  INDEX uid (uid ASC) VISIBLE,
  FULLTEXT INDEX subject (subject) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_threadsread (
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  UNIQUE INDEX tid (tid ASC, uid ASC) VISIBLE,
  INDEX dateline (dateline ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_threadsubscriptions (
  sid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  notification TINYINT(1) NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (sid),
  INDEX uid (uid ASC) VISIBLE,
  INDEX tid (tid ASC, notification ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_threadviews (
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  INDEX tid (tid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_userfields (
  ufid INT UNSIGNED NOT NULL DEFAULT '0',
  fid1 TEXT NOT NULL,
  fid2 TEXT NOT NULL,
  fid3 TEXT NOT NULL,
  PRIMARY KEY (ufid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_usergroups (
  gid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  type TINYINT UNSIGNED NOT NULL DEFAULT '2',
  title VARCHAR(120) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  namestyle VARCHAR(200) NOT NULL DEFAULT '{username}',
  usertitle VARCHAR(120) NOT NULL DEFAULT '',
  stars SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  starimage VARCHAR(120) NOT NULL DEFAULT '',
  image VARCHAR(120) NOT NULL DEFAULT '',
  disporder SMALLINT UNSIGNED NOT NULL,
  isbannedgroup TINYINT(1) NOT NULL DEFAULT '0',
  canview TINYINT(1) NOT NULL DEFAULT '0',
  canviewthreads TINYINT(1) NOT NULL DEFAULT '0',
  canviewprofiles TINYINT(1) NOT NULL DEFAULT '0',
  candlattachments TINYINT(1) NOT NULL DEFAULT '0',
  canviewboardclosed TINYINT(1) NOT NULL DEFAULT '0',
  canpostthreads TINYINT(1) NOT NULL DEFAULT '0',
  canpostreplys TINYINT(1) NOT NULL DEFAULT '0',
  canpostattachments TINYINT(1) NOT NULL DEFAULT '0',
  canratethreads TINYINT(1) NOT NULL DEFAULT '0',
  modposts TINYINT(1) NOT NULL DEFAULT '0',
  modthreads TINYINT(1) NOT NULL DEFAULT '0',
  mod_edit_posts TINYINT(1) NOT NULL DEFAULT '0',
  modattachments TINYINT(1) NOT NULL DEFAULT '0',
  caneditposts TINYINT(1) NOT NULL DEFAULT '0',
  candeleteposts TINYINT(1) NOT NULL DEFAULT '0',
  candeletethreads TINYINT(1) NOT NULL DEFAULT '0',
  caneditattachments TINYINT(1) NOT NULL DEFAULT '0',
  canviewdeletionnotice TINYINT(1) NOT NULL DEFAULT '0',
  canpostpolls TINYINT(1) NOT NULL DEFAULT '0',
  canvotepolls TINYINT(1) NOT NULL DEFAULT '0',
  canundovotes TINYINT(1) NOT NULL DEFAULT '0',
  canusepms TINYINT(1) NOT NULL DEFAULT '0',
  cansendpms TINYINT(1) NOT NULL DEFAULT '0',
  cantrackpms TINYINT(1) NOT NULL DEFAULT '0',
  candenypmreceipts TINYINT(1) NOT NULL DEFAULT '0',
  pmquota INT UNSIGNED NOT NULL DEFAULT '0',
  maxpmrecipients INT UNSIGNED NOT NULL DEFAULT '5',
  cansendemail TINYINT(1) NOT NULL DEFAULT '0',
  cansendemailoverride TINYINT(1) NOT NULL DEFAULT '0',
  maxemails INT UNSIGNED NOT NULL DEFAULT '5',
  emailfloodtime INT UNSIGNED NOT NULL DEFAULT '5',
  canviewmemberlist TINYINT(1) NOT NULL DEFAULT '0',
  canviewcalendar TINYINT(1) NOT NULL DEFAULT '0',
  canaddevents TINYINT(1) NOT NULL DEFAULT '0',
  canbypasseventmod TINYINT(1) NOT NULL DEFAULT '0',
  canmoderateevents TINYINT(1) NOT NULL DEFAULT '0',
  canviewonline TINYINT(1) NOT NULL DEFAULT '0',
  canviewwolinvis TINYINT(1) NOT NULL DEFAULT '0',
  canviewonlineips TINYINT(1) NOT NULL DEFAULT '0',
  cancp TINYINT(1) NOT NULL DEFAULT '0',
  issupermod TINYINT(1) NOT NULL DEFAULT '0',
  cansearch TINYINT(1) NOT NULL DEFAULT '0',
  canusercp TINYINT(1) NOT NULL DEFAULT '0',
  canuploadavatars TINYINT(1) NOT NULL DEFAULT '0',
  canratemembers TINYINT(1) NOT NULL DEFAULT '0',
  canchangename TINYINT(1) NOT NULL DEFAULT '0',
  canbereported TINYINT(1) NOT NULL DEFAULT '0',
  canchangewebsite TINYINT(1) NOT NULL DEFAULT '1',
  showforumteam TINYINT(1) NOT NULL DEFAULT '0',
  usereputationsystem TINYINT(1) NOT NULL DEFAULT '0',
  cangivereputations TINYINT(1) NOT NULL DEFAULT '0',
  candeletereputations TINYINT(1) NOT NULL DEFAULT '0',
  reputationpower INT UNSIGNED NOT NULL DEFAULT '0',
  maxreputationsday INT UNSIGNED NOT NULL DEFAULT '0',
  maxreputationsperuser INT UNSIGNED NOT NULL DEFAULT '0',
  maxreputationsperthread INT UNSIGNED NOT NULL DEFAULT '0',
  candisplaygroup TINYINT(1) NOT NULL DEFAULT '0',
  attachquota INT UNSIGNED NOT NULL DEFAULT '0',
  cancustomtitle TINYINT(1) NOT NULL DEFAULT '0',
  canwarnusers TINYINT(1) NOT NULL DEFAULT '0',
  canreceivewarnings TINYINT(1) NOT NULL DEFAULT '0',
  maxwarningsday INT UNSIGNED NOT NULL DEFAULT '3',
  canmodcp TINYINT(1) NOT NULL DEFAULT '0',
  showinbirthdaylist TINYINT(1) NOT NULL DEFAULT '0',
  canoverridepm TINYINT(1) NOT NULL DEFAULT '0',
  canusesig TINYINT(1) NOT NULL DEFAULT '0',
  canusesigxposts SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  signofollow TINYINT(1) NOT NULL DEFAULT '0',
  edittimelimit INT UNSIGNED NOT NULL DEFAULT '0',
  maxposts INT UNSIGNED NOT NULL DEFAULT '0',
  showmemberlist TINYINT(1) NOT NULL DEFAULT '1',
  canmanageannounce TINYINT(1) NOT NULL DEFAULT '0',
  canmanagemodqueue TINYINT(1) NOT NULL DEFAULT '0',
  canmanagereportedcontent TINYINT(1) NOT NULL DEFAULT '0',
  canviewmodlogs TINYINT(1) NOT NULL DEFAULT '0',
  caneditprofiles TINYINT(1) NOT NULL DEFAULT '0',
  canbanusers TINYINT(1) NOT NULL DEFAULT '0',
  canviewwarnlogs TINYINT(1) NOT NULL DEFAULT '0',
  canuseipsearch TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (gid))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_users (
  uid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(120) NOT NULL DEFAULT '',
  password VARCHAR(120) NOT NULL DEFAULT '',
  salt VARCHAR(10) NOT NULL DEFAULT '',
  loginkey VARCHAR(50) NOT NULL DEFAULT '',
  email VARCHAR(220) NOT NULL DEFAULT '',
  postnum INT UNSIGNED NOT NULL DEFAULT '0',
  threadnum INT UNSIGNED NOT NULL DEFAULT '0',
  avatar VARCHAR(200) NOT NULL DEFAULT '',
  avatardimensions VARCHAR(10) NOT NULL DEFAULT '',
  avatartype VARCHAR(10) NOT NULL DEFAULT '0',
  usergroup SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  additionalgroups VARCHAR(200) NOT NULL DEFAULT '',
  displaygroup SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  usertitle VARCHAR(250) NOT NULL DEFAULT '',
  regdate INT UNSIGNED NOT NULL DEFAULT '0',
  lastactive INT UNSIGNED NOT NULL DEFAULT '0',
  lastvisit INT UNSIGNED NOT NULL DEFAULT '0',
  lastpost INT UNSIGNED NOT NULL DEFAULT '0',
  website VARCHAR(200) NOT NULL DEFAULT '',
  icq VARCHAR(10) NOT NULL DEFAULT '',
  skype VARCHAR(75) NOT NULL DEFAULT '',
  google VARCHAR(75) NOT NULL DEFAULT '',
  birthday VARCHAR(15) NOT NULL DEFAULT '',
  birthdayprivacy VARCHAR(4) NOT NULL DEFAULT 'all',
  signature TEXT NOT NULL,
  allownotices TINYINT(1) NOT NULL DEFAULT '0',
  hideemail TINYINT(1) NOT NULL DEFAULT '0',
  subscriptionmethod TINYINT(1) NOT NULL DEFAULT '0',
  invisible TINYINT(1) NOT NULL DEFAULT '0',
  receivepms TINYINT(1) NOT NULL DEFAULT '0',
  receivefrombuddy TINYINT(1) NOT NULL DEFAULT '0',
  pmnotice TINYINT(1) NOT NULL DEFAULT '0',
  pmnotify TINYINT(1) NOT NULL DEFAULT '0',
  buddyrequestspm TINYINT(1) NOT NULL DEFAULT '1',
  buddyrequestsauto TINYINT(1) NOT NULL DEFAULT '0',
  threadmode VARCHAR(8) NOT NULL DEFAULT '',
  showimages TINYINT(1) NOT NULL DEFAULT '0',
  showvideos TINYINT(1) NOT NULL DEFAULT '0',
  showsigs TINYINT(1) NOT NULL DEFAULT '0',
  showavatars TINYINT(1) NOT NULL DEFAULT '0',
  showquickreply TINYINT(1) NOT NULL DEFAULT '0',
  showredirect TINYINT(1) NOT NULL DEFAULT '0',
  ppp SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  tpp SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  daysprune SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  dateformat VARCHAR(4) NOT NULL DEFAULT '',
  timeformat VARCHAR(4) NOT NULL DEFAULT '',
  timezone VARCHAR(5) NOT NULL DEFAULT '',
  dst TINYINT(1) NOT NULL DEFAULT '0',
  dstcorrection TINYINT(1) NOT NULL DEFAULT '0',
  buddylist TEXT NOT NULL,
  ignorelist TEXT NOT NULL,
  style SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  away TINYINT(1) NOT NULL DEFAULT '0',
  awaydate INT UNSIGNED NOT NULL DEFAULT '0',
  returndate VARCHAR(15) NOT NULL DEFAULT '',
  awayreason VARCHAR(200) NOT NULL DEFAULT '',
  pmfolders TEXT NOT NULL,
  notepad TEXT NOT NULL,
  referrer INT UNSIGNED NOT NULL DEFAULT '0',
  referrals INT UNSIGNED NOT NULL DEFAULT '0',
  reputation INT NOT NULL DEFAULT '0',
  regip VARBINARY(16) NOT NULL DEFAULT '',
  lastip VARBINARY(16) NOT NULL DEFAULT '',
  language VARCHAR(50) NOT NULL DEFAULT '',
  timeonline INT UNSIGNED NOT NULL DEFAULT '0',
  showcodebuttons TINYINT(1) NOT NULL DEFAULT '1',
  totalpms INT UNSIGNED NOT NULL DEFAULT '0',
  unreadpms INT UNSIGNED NOT NULL DEFAULT '0',
  warningpoints INT UNSIGNED NOT NULL DEFAULT '0',
  moderateposts TINYINT(1) NOT NULL DEFAULT '0',
  moderationtime INT UNSIGNED NOT NULL DEFAULT '0',
  suspendposting TINYINT(1) NOT NULL DEFAULT '0',
  suspensiontime INT UNSIGNED NOT NULL DEFAULT '0',
  suspendsignature TINYINT(1) NOT NULL DEFAULT '0',
  suspendsigtime INT UNSIGNED NOT NULL DEFAULT '0',
  coppauser TINYINT(1) NOT NULL DEFAULT '0',
  classicpostbit TINYINT(1) NOT NULL DEFAULT '0',
  loginattempts SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  loginlockoutexpiry INT UNSIGNED NOT NULL DEFAULT '0',
  usernotes TEXT NOT NULL,
  sourceeditor TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (uid),
  UNIQUE INDEX username (username ASC) VISIBLE,
  INDEX usergroup (usergroup ASC) VISIBLE,
  INDEX regip (regip ASC) VISIBLE,
  INDEX lastip (lastip ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_usertitles (
  utid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  posts INT UNSIGNED NOT NULL DEFAULT '0',
  title VARCHAR(250) NOT NULL DEFAULT '',
  stars SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  starimage VARCHAR(120) NOT NULL DEFAULT '',
  PRIMARY KEY (utid))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_warninglevels (
  lid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  percentage SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  action TEXT NOT NULL,
  PRIMARY KEY (lid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_warnings (
  wid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT UNSIGNED NOT NULL DEFAULT '0',
  tid INT UNSIGNED NOT NULL DEFAULT '0',
  pid INT UNSIGNED NOT NULL DEFAULT '0',
  title VARCHAR(120) NOT NULL DEFAULT '',
  points SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  dateline INT UNSIGNED NOT NULL DEFAULT '0',
  issuedby INT UNSIGNED NOT NULL DEFAULT '0',
  expires INT UNSIGNED NOT NULL DEFAULT '0',
  expired TINYINT(1) NOT NULL DEFAULT '0',
  daterevoked INT UNSIGNED NOT NULL DEFAULT '0',
  revokedby INT UNSIGNED NOT NULL DEFAULT '0',
  revokereason TEXT NOT NULL,
  notes TEXT NOT NULL,
  PRIMARY KEY (wid),
  INDEX uid (uid ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS flsolutions_warningtypes (
  tid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(120) NOT NULL DEFAULT '',
  points SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  expirationtime INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (tid))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS log_controller (
  id_log_controller INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id_log_controller))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS login (
  id_login INT NOT NULL AUTO_INCREMENT,
  date_login INT NOT NULL,
  PRIMARY KEY (id_login))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS log (
  id_log INT NOT NULL AUTO_INCREMENT,
  id_log_controller INT NOT NULL,
  id_colaborator INT NOT NULL,
  id_login INT NOT NULL,
  PRIMARY KEY (id_log),
  INDEX fk_log_log_controller_idx (id_log_controller ASC) VISIBLE,
  INDEX fk_log_colaborator1_idx (id_colaborator ASC) VISIBLE,
  INDEX fk_log_login1_idx (id_login ASC) VISIBLE,
  CONSTRAINT fk_log_colaborator
    FOREIGN KEY (id_colaborator)
    REFERENCES colaborator (id_colaborator)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_log_log_controller
    FOREIGN KEY (id_log_controller)
    REFERENCES log_controller (id_log_controller)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_log_login
    FOREIGN KEY (id_login)
    REFERENCES login (id_login)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payment_type (
  id_payment_type INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id_payment_type))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payment_order (
  id_payment_order INT NOT NULL AUTO_INCREMENT,
  id_payment_type INT NOT NULL,
  PRIMARY KEY (id_payment_order),
  INDEX fk_payment_order_payment_type_idx (id_payment_type ASC) VISIBLE,
  CONSTRAINT fk_payment_order_payment_type
    FOREIGN KEY (id_payment_type)
    REFERENCES payment_type (id_payment_type)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payment (
  id_payment INT NOT NULL AUTO_INCREMENT,
  id_payment_order INT NOT NULL,
  PRIMARY KEY (id_payment),
  INDEX fk_payment_payment_order_idx (id_payment_order ASC) VISIBLE,
  CONSTRAINT fk_payment_payment_order
    FOREIGN KEY (id_payment_order)
    REFERENCES payment_order (id_payment_order)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payment_order_has_colaborator (
  id_payment_order INT NOT NULL,
  id_payment_type INT NOT NULL,
  id_colaborator INT NOT NULL,
  id_colaborator_type INT NOT NULL,
  PRIMARY KEY (id_payment_order),
  INDEX fk_payment_order_has_colaborator_colaborator_idx (id_colaborator ASC) VISIBLE,
  INDEX fk_payment_order_has_colaborator_payment_order_idx (id_payment_order ASC) VISIBLE,
  CONSTRAINT fk_payment_order_has_colaborator_colaborator
    FOREIGN KEY (id_colaborator)
    REFERENCES colaborator (id_colaborator)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_payment_order_has_colaborator_payment_order
    FOREIGN KEY (id_payment_order)
    REFERENCES payment_order (id_payment_order)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS tutorial_type (
  id_tutorial_type INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id_tutorial_type))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS tutorial (
  id_tutorial INT NOT NULL,
  id_payment_order INT NOT NULL,
  id_payment_type INT NOT NULL,
  PRIMARY KEY (id_tutorial),
  INDEX fk_tutorial_type_has_user_tutorial_type_idx (id_tutorial ASC) VISIBLE,
  INDEX fk_tutorial_type_has_user_payment_order_idx (id_payment_order ASC) VISIBLE,
  CONSTRAINT fk_tutorial_type_has_user_payment_order
    FOREIGN KEY (id_payment_order)
    REFERENCES payment_order (id_payment_order)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_tutorial_type_has_user_tutorial_type
    FOREIGN KEY (id_tutorial)
    REFERENCES tutorial_type (id_tutorial_type))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS tutorial_item (
  id_tutorial_item INT NOT NULL AUTO_INCREMENT,
  id_tutorial INT NOT NULL,
  PRIMARY KEY (id_tutorial_item),
  INDEX fk_tutorial_item_tutorial1_idx (id_tutorial ASC) VISIBLE,
  CONSTRAINT fk_tutorial_item_tutorial
    FOREIGN KEY (id_tutorial)
    REFERENCES tutorial (id_tutorial)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_address (
  id_client_address INT NOT NULL AUTO_INCREMENT,
  cep INT NULL DEFAULT NULL,
  street VARCHAR(100) NULL DEFAULT NULL,
  number INT NULL DEFAULT NULL,
  district VARCHAR(100) NULL DEFAULT NULL,
  city VARCHAR(45) NULL DEFAULT NULL,
  state VARCHAR(45) NULL DEFAULT NULL,
  country VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (id_client_address))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_type (
  id_user_type INT NOT NULL AUTO_INCREMENT,
  name_type VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (id_user_type))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user (
  id_user INT NOT NULL AUTO_INCREMENT,
  id_user_type INT NOT NULL,
  id_client_address INT NOT NULL,
  id_login INT NOT NULL,
  id_log INT NOT NULL,
  firstname VARCHAR(45) NULL DEFAULT NULL,
  lastname VARCHAR(45) NULL DEFAULT NULL,
  cpf INT NULL DEFAULT NULL,
  rg INT NULL DEFAULT NULL,
  PRIMARY KEY (id_user),
  INDEX fk_user_user_type_idx (id_user_type ASC) VISIBLE,
  INDEX fk_user_user_address_idx (id_client_address ASC) VISIBLE,
  INDEX fk_user_login_idx (id_login ASC) VISIBLE,
  CONSTRAINT fk_user_login
    FOREIGN KEY (id_login)
    REFERENCES login (id_login)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_user_user_address
    FOREIGN KEY (id_client_address)
    REFERENCES user_address (id_client_address)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_user_user_type
    FOREIGN KEY (id_user_type)
    REFERENCES user_type (id_user_type)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_interest (
  id_user_interest INT NOT NULL AUTO_INCREMENT,
  id_user INT NOT NULL,
  PRIMARY KEY (id_user_interest),
  INDEX fk_user_interest_user_idx (id_user ASC) VISIBLE,
  CONSTRAINT fk_user_interest_user
    FOREIGN KEY (id_user)
    REFERENCES user (id_user)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_permission (
  id_user_permission INT NOT NULL AUTO_INCREMENT,
  id_user INT NOT NULL,
  id_user_type INT NOT NULL,
  id_client_address INT NOT NULL,
  PRIMARY KEY (id_user_permission),
  INDEX fk_user_permission_user_idx (id_user ASC) VISIBLE,
  CONSTRAINT fk_user_permission_user
    FOREIGN KEY (id_user)
    REFERENCES user (id_user)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS view_tutorial (
  id_view_tutorial INT NOT NULL AUTO_INCREMENT,
  id_user INT NOT NULL,
  id_payment INT NOT NULL,
  PRIMARY KEY (id_view_tutorial),
  INDEX fk_view_tutorial_user_idx (id_user ASC) VISIBLE,
  INDEX fk_view_tutorial_payment_idx (id_payment ASC) VISIBLE,
  CONSTRAINT fk_view_tutorial_payment
    FOREIGN KEY (id_payment)
    REFERENCES payment (id_payment)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_view_tutorial_user
    FOREIGN KEY (id_user)
    REFERENCES user (id_user)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;